// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyVocabulary.Infrastructure.Data;

#nullable disable

namespace MyVocabulary.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250130091210_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("MyVocabulary.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureFrom")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureTo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Header");

                    b.HasIndex("Header", "CultureFrom", "CultureTo");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("MyVocabulary.Domain.Entities.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WordUsageId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordUsageId");

                    b.HasIndex("WordUsageId", "IsRight");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("MyVocabulary.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.HasIndex("Culture", "Value")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("MyVocabulary.Domain.Entities.WordUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeSentence")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NativeWordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSentence")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranslationWordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NativeWordId");

                    b.HasIndex("TopicId");

                    b.HasIndex("TranslationWordId");

                    b.ToTable("WordUsages");
                });

            modelBuilder.Entity("MyVocabulary.Domain.Entities.UserAnswer", b =>
                {
                    b.HasOne("MyVocabulary.Domain.Entities.WordUsage", null)
                        .WithMany()
                        .HasForeignKey("WordUsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyVocabulary.Domain.Entities.WordUsage", b =>
                {
                    b.HasOne("MyVocabulary.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("NativeWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyVocabulary.Domain.Entities.Topic", null)
                        .WithMany("WordUsages")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyVocabulary.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("TranslationWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyVocabulary.Domain.Entities.Topic", b =>
                {
                    b.Navigation("WordUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
