//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVocabulary.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyVocabulary.UI.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phrase usage.
        /// </summary>
        internal static string AddPhraseUsage {
            get {
                return ResourceManager.GetString("AddPhraseUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazing topic....
        /// </summary>
        internal static string AmazingTopic {
            get {
                return ResourceManager.GetString("AmazingTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose correct translation.
        /// </summary>
        internal static string ChooseCorrectTranslation {
            get {
                return ResourceManager.GetString("ChooseCorrectTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image URL:.
        /// </summary>
        internal static string EnterImageURL {
            get {
                return ResourceManager.GetString("EnterImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix mistakes.
        /// </summary>
        internal static string FixMistakes {
            get {
                return ResourceManager.GetString("FixMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language from.
        /// </summary>
        internal static string LanguageFrom {
            get {
                return ResourceManager.GetString("LanguageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language to.
        /// </summary>
        internal static string LanguageTo {
            get {
                return ResourceManager.GetString("LanguageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn new words.
        /// </summary>
        internal static string LearnNewWords {
            get {
                return ResourceManager.GetString("LearnNewWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        internal static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyVocabulary.
        /// </summary>
        internal static string MyVocabulary {
            get {
                return ResourceManager.GetString("MyVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native sentence....
        /// </summary>
        internal static string NativeSentence {
            get {
                return ResourceManager.GetString("NativeSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No phrase usages....
        /// </summary>
        internal static string NoPhraseUsages {
            get {
                return ResourceManager.GetString("NoPhraseUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase.
        /// </summary>
        internal static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrases.
        /// </summary>
        internal static string Phrases {
            get {
                return ResourceManager.GetString("Phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase usage.
        /// </summary>
        internal static string PhraseUsage {
            get {
                return ResourceManager.GetString("PhraseUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phrase....
        /// </summary>
        internal static string PlaceholderPhrase {
            get {
                return ResourceManager.GetString("PlaceholderPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation....
        /// </summary>
        internal static string PlaceholderTranslation {
            get {
                return ResourceManager.GetString("PlaceholderTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice it.
        /// </summary>
        internal static string PracticeIt {
            get {
                return ResourceManager.GetString("PracticeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember translation.
        /// </summary>
        internal static string RememberTranslation {
            get {
                return ResourceManager.GetString("RememberTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search topics ....
        /// </summary>
        internal static string SearchTextPlaceholder {
            get {
                return ResourceManager.GetString("SearchTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        internal static string StartLesson {
            get {
                return ResourceManager.GetString("StartLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic description....
        /// </summary>
        internal static string TopicDescription {
            get {
                return ResourceManager.GetString("TopicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic name.
        /// </summary>
        internal static string TopicName {
            get {
                return ResourceManager.GetString("TopicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        internal static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated sentence....
        /// </summary>
        internal static string TranslatedSentence {
            get {
                return ResourceManager.GetString("TranslatedSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User answers.
        /// </summary>
        internal static string UserAnswers {
            get {
                return ResourceManager.GetString("UserAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
